server:
  port: 80

# 注册Eureka服务
eureka:
  client:
    # Eureka服务注册中心会将自己作为客户端来尝试注册它自己，必須禁止
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

#设置feign 客户端超时时间


spring:
  application:
    name: cloud-order-feign-hystrix-80

#开启
feign:
  hystrix:
    enabled: true